file=open("Output.txt","w")
text=input("Enter text to write into the file: ")
file.write(text+'\n')
print("Data successfully written to Output.txt.")
file=open("Output.txt","a")
text=input("Enter additional text to append: ")
file.write(text)
print("Data successfully appended.")
print("Final content of output.txt:")
file=open("Output.txt",'r')
print(file.read())